version: '3.8'
services:
  mysql:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - spring-demo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mail-dev:
    container_name: mail-dev-wms
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  wms-backend:
    container_name: wms-api
    image: ${DOCKERHUB_USERNAME}/wms-api:latest
    ports:
      - 8088:8088
    environment:
      - EMAIL_HOSTNAME=${EMAIL_HOSTNAME}
      - EMAIL_USER_NAME=${EMAIL_USER_NAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - spring-demo
    depends_on:
      - mysql
    restart: always

  wms-frontend:
    container_name: wms-ui
    image: ${DOCKERHUB_USERNAME}/wms-ui:latest
    ports:
      - 80:80
    networks:
      - spring-demo
    depends_on:
      - wms-backend
    restart: always

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local