services:
  mysql:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  wm-api:
    container_name: wm-api
    image: dwm/dwm:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - mysql

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
