/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyClassResponse } from '../../models/my-class-response';

export interface FindAllMyClass$Params {
}

export function findAllMyClass(http: HttpClient, rootUrl: string, params?: FindAllMyClass$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MyClassResponse>>> {
  const rb = new RequestBuilder(rootUrl, findAllMyClass.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MyClassResponse>>;
    })
  );
}

findAllMyClass.PATH = '/my-class';
