/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatusTypeResponse } from '../../models/status-type-response';

export interface FindAllStatusTypes$Params {
}

export function findAllStatusTypes(http: HttpClient, rootUrl: string, params?: FindAllStatusTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StatusTypeResponse>>> {
  const rb = new RequestBuilder(rootUrl, findAllStatusTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatusTypeResponse>>;
    })
  );
}

findAllStatusTypes.PATH = '/status-type';
