/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatusTypeResponse } from '../../models/status-type-response';

export interface FindStatusTypeById$Params {
  statusTypeId: number;
}

export function findStatusTypeById(http: HttpClient, rootUrl: string, params: FindStatusTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, findStatusTypeById.PATH, 'get');
  if (params) {
    rb.path('statusTypeId', params.statusTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatusTypeResponse>;
    })
  );
}

findStatusTypeById.PATH = '/status-type/{statusTypeId}';
