/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AcademicRank } from './models/academic-rank';
export { AcademicRankDetails } from './models/academic-rank-details';
export { AcademicRankDetailsRequest } from './models/academic-rank-details-request';
export { AcademicRankDetailsResponse } from './models/academic-rank-details-response';
export { AcademicRankRequest } from './models/academic-rank-request';
export { AcademicRankResponse } from './models/academic-rank-response';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { Course } from './models/course';
export { CourseRequest } from './models/course-request';
export { CourseResponse } from './models/course-response';
export { Faculty } from './models/faculty';
export { FacultyRequest } from './models/faculty-request';
export { FacultyResponse } from './models/faculty-response';
export { GrantedAuthority } from './models/granted-authority';
export { MyClassRequest } from './models/my-class-request';
export { MyClassResponse } from './models/my-class-response';
export { MyUser } from './models/my-user';
export { PageResponseWorkloadResponse } from './models/page-response-workload-response';
export { RegistrationRequest } from './models/registration-request';
export { Semester } from './models/semester';
export { SemesterRequest } from './models/semester-request';
export { SemesterResponse } from './models/semester-response';
export { StatusType } from './models/status-type';
export { StatusTypeRequest } from './models/status-type-request';
export { StatusTypeResponse } from './models/status-type-response';
export { TeachingStaff } from './models/teaching-staff';
export { TeachingStaffRequest } from './models/teaching-staff-request';
export { TeachingStaffResponse } from './models/teaching-staff-response';
export { WorkloadRequest } from './models/workload-request';
export { WorkloadResponse } from './models/workload-response';
