/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { WorkloadService } from './services/workload.service';
export { TeachingStaffService } from './services/teaching-staff.service';
export { SemesterControllerService } from './services/semester-controller.service';
export { StatusTypeService } from './services/status-type.service';
export { MyClassService } from './services/my-class.service';
export { FacultyService } from './services/faculty.service';
export { CourseService } from './services/course.service';
export { AuthenticationService } from './services/authentication.service';
export { AcademicRankService } from './services/academic-rank.service';
