/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicRankResponse {
  abbreviation?: string;
  academicRankId?: number;
  cpForFullTime?: number;
  rankName?: string;
  salary?: number;
}
