/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicRankResponse {
  abbreviation?: string;
  academicRankId?: number;
  deleted?: boolean;
  rankName?: string;
}
