/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicRankRequest {
  abbreviation: string;
  cpForFullTime: number;
  rankName: string;
  salary: number;
  semester: 'pavasaris' | 'rudens';
}
