/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicRank {
  abbreviation?: string;
  academicRankId?: number;
  rankName?: string;
}
