/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcademicRankDetailsRequest {
  academicRankId: number;
  contactHoursForFullTime: number;
  cpForFullTime: number;
  salary: number;
  semesterId: number;
}
