/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRank } from '../models/academic-rank';
import { Semester } from '../models/semester';
export interface AcademicRankDetailsResponse {
  academicRank?: AcademicRank;
  academicRankDetailsId?: number;
  contactHoursForFullTime?: number;
  cpForFullTime?: number;
  salary?: number;
  semester?: Semester;
}
