/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRank } from '../models/academic-rank';
export interface CourseResponse {
  courseCode?: string;
  courseId?: number;
  courseName?: string;
  creditPoints?: number;
  deleted?: boolean;
  necessaryAcademicRank?: AcademicRank;
  registrationType?: string;
  section?: string;
  studyLevel?: number;
}
