/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseResponse {
  courseCode?: string;
  courseId?: number;
  courseName?: string;
  creditPoints?: number;
  deleted?: boolean;
  registrationType?: string;
  section?: string;
}
