/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRankResponse } from '../models/academic-rank-response';
export interface CourseRequest {
  courseCode: string;
  courseName: string;
  creditPoints: number;
  necessaryAcademicRank: AcademicRankResponse;
  registrationType: string;
  section: string;
  studyLevel: number;
}
