/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseRequest {
  courseCode: string;
  courseName: string;
  creditPoints: number;
  necessaryAcademicRankId: number;
  registrationType: string;
  section: string;
  studyLevel: number;
}
