/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Faculty {
  facultyId?: number;
  facultyName?: string;
  faculty_full_name?: string;
}
