/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FacultyResponse {
  facultyFullName?: string;
  facultyId?: number;
  facultyName?: string;
}
