/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MyClassRequest {
  classFacultyId: number;
  classLevel: number;
  degree: 'BACHELOR' | 'MASTER' | 'DOCTORATE';
  myClassProgram: string;
}
