/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MyClassRequest {
  classFacultyId: number;
  className: string;
  classYear: string;
  program?: string;
  studentAmount?: number;
  studyYear: number;
}
