/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Faculty } from '../models/faculty';
export interface MyClassRequest {
  classFaculty: Faculty;
  className: string;
  classYear: string;
  studentAmount?: number;
  studyYear: number;
}
