/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Faculty } from '../models/faculty';
export interface MyClass {
  classFaculty?: Faculty;
  classId?: number;
  className?: string;
  classYear?: string;
  studentAmount?: number;
}
