/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { TeachingStaff } from '../models/teaching-staff';
export interface MyUser {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email: string;
  enabled?: boolean;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  password?: string;
  teachingStaff?: TeachingStaff;
  username?: string;
}
