/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Semester {
  deleted?: boolean;
  semesterId?: number;
  semesterName?: 'PAVASARIS' | 'RUDENS';
  semesterYear?: number;
}
