/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SemesterResponse {
  deleted?: boolean;
  semesterId?: number;
  semesterName?: 'pavasaris' | 'rudens';
  year?: number;
}
