/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatusType {
  deleted?: boolean;
  statusTypeId?: number;
  statusTypeName?: string;
}
