/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRank } from '../models/academic-rank';
import { Faculty } from '../models/faculty';
import { MyUser } from '../models/my-user';
export interface TeachingStaffResponse {
  positionTitle?: string;
  rankFullName?: string;
  staffAcademicRank?: AcademicRank;
  staffFaculty?: Faculty;
  staffFullName?: string;
  staffPhoto?: string;
  teachingStaffId?: number;
  user?: MyUser;
}
