/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRankResponse } from '../models/academic-rank-response';
import { FacultyResponse } from '../models/faculty-response';
import { RegistrationRequest } from '../models/registration-request';
export interface TeachingStaffRequest {
  authDetails?: RegistrationRequest;
  name: string;
  positionTitle: string;
  staffAcademicRank: AcademicRankResponse;
  staffFaculty: FacultyResponse;
  surname: string;
}
