/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkloadSettingsResponse {
  default?: boolean;
  settingName?: string;
  visibleColumns?: Array<string>;
  workloadSettingsId?: number;
}
