/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRank } from '../models/academic-rank';
import { Course } from '../models/course';
import { MyClass } from '../models/my-class';
import { StatusType } from '../models/status-type';
import { TeachingStaff } from '../models/teaching-staff';
export interface WorkloadRequest {
  academicRank: AcademicRank;
  budgetPosition: boolean;
  comments: string;
  contactHours: number;
  course: Course;
  expectedSalary: number;
  groupAmount: number;
  groupForSemester: string;
  includeInBudget: string;
  industryCoefficient: number;
  myClasses: Array<MyClass>;
  program: string;
  semester: string;
  statusType: StatusType;
  teachingStaff: TeachingStaff;
  vacationMonths: number;
  workingMonths: number;
}
