/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRankDetails } from '../models/academic-rank-details';
import { Course } from '../models/course';
import { MyClass } from '../models/my-class';
import { MyClassResponse } from '../models/my-class-response';
import { Semester } from '../models/semester';
import { StatusType } from '../models/status-type';
import { TeachingStaff } from '../models/teaching-staff';
export interface WorkloadResponse {
  academicRankDetails?: AcademicRankDetails;
  budgetPosition?: boolean;
  comments?: string;
  contactHours?: number;
  course?: Course;
  cpForFullTime?: number;
  cpProportionOnFullTime?: number;
  creditPointsPerGroup?: number;
  creditPointsPerHour?: number;
  expectedSalary?: number;
  groupAmount?: number;
  groupForSemester?: MyClassResponse;
  includeInBudget?: string;
  industryCoefficient?: number;
  monthSum?: number;
  myClasses?: Array<MyClass>;
  program?: string;
  salaryPerMonth?: number;
  semester?: Semester;
  statusType?: StatusType;
  teachingStaff?: TeachingStaff;
  vacationMonths?: number;
  workloadId?: number;
}
