/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademicRankDetails } from '../models/academic-rank-details';
import { Course } from '../models/course';
import { MyClassResponse } from '../models/my-class-response';
import { Semester } from '../models/semester';
import { TeachingStaff } from '../models/teaching-staff';
export interface WorkloadResponse {
  academicRankDetails?: AcademicRankDetails;
  budgetPosition?: 'ZB' | 'PF' | 'M' | 'grant';
  comments?: string;
  contactHours?: number;
  course?: Course;
  cpForFullTime?: number;
  cpProportionOnFullTime?: number;
  creditPointsPerGroup?: number;
  expectedSalary?: number;
  groupAmount?: number;
  groupForSemester?: MyClassResponse;
  includeInBudget?: string;
  industryCoefficient?: number;
  monthSum?: number;
  myClasses?: Array<MyClassResponse>;
  programCoefficient?: number;
  salaryPerMonth?: number;
  semester?: Semester;
  teachingStaff?: TeachingStaff;
  totalCreditPoints?: number;
  vacationMonths?: number;
  workloadId?: number;
}
