/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkloadRequest {
  academicRankId: number;
  budgetPosition: boolean;
  comments: string;
  contactHours: number;
  courseId: number;
  expectedSalary: number;
  groupAmount: number;
  groupForSemesterId: number;
  includeInBudget: string;
  industryCoefficient: number;
  myClassIds: Array<number>;
  program: string;
  semesterId: number;
  statusTypeId: number;
  teachingStaffId: number;
  vacationMonths: number;
  workingMonths?: number;
}
