/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkloadSettingsRequest {
  isDefault?: boolean;
  isGlobal?: boolean;
  settingName?: string;
  visibleColumns?: Array<string>;
}
