/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FacultyResponse } from '../models/faculty-response';
import { getFaculties } from '../fn/faculty/get-faculties';
import { GetFaculties$Params } from '../fn/faculty/get-faculties';
import { getFaculty } from '../fn/faculty/get-faculty';
import { GetFaculty$Params } from '../fn/faculty/get-faculty';
import { saveFaculty } from '../fn/faculty/save-faculty';
import { SaveFaculty$Params } from '../fn/faculty/save-faculty';

@Injectable({ providedIn: 'root' })
export class FacultyService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFaculties()` */
  static readonly GetFacultiesPath = '/faculty';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFaculties()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFaculties$Response(params?: GetFaculties$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FacultyResponse>>> {
    return getFaculties(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFaculties$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFaculties(params?: GetFaculties$Params, context?: HttpContext): Observable<Array<FacultyResponse>> {
    return this.getFaculties$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FacultyResponse>>): Array<FacultyResponse> => r.body)
    );
  }

  /** Path part for operation `saveFaculty()` */
  static readonly SaveFacultyPath = '/faculty';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFaculty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFaculty$Response(params: SaveFaculty$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveFaculty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFaculty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFaculty(params: SaveFaculty$Params, context?: HttpContext): Observable<number> {
    return this.saveFaculty$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getFaculty()` */
  static readonly GetFacultyPath = '/faculty/{facultyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFaculty()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFaculty$Response(params: GetFaculty$Params, context?: HttpContext): Observable<StrictHttpResponse<FacultyResponse>> {
    return getFaculty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFaculty$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFaculty(params: GetFaculty$Params, context?: HttpContext): Observable<FacultyResponse> {
    return this.getFaculty$Response(params, context).pipe(
      map((r: StrictHttpResponse<FacultyResponse>): FacultyResponse => r.body)
    );
  }

}
