/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { copyAcademicRanksFromSemester } from '../fn/semester-controller/copy-academic-ranks-from-semester';
import { CopyAcademicRanksFromSemester$Params } from '../fn/semester-controller/copy-academic-ranks-from-semester';
import { copyWorkloadsFromSemester } from '../fn/semester-controller/copy-workloads-from-semester';
import { CopyWorkloadsFromSemester$Params } from '../fn/semester-controller/copy-workloads-from-semester';
import { deleteSemesterById } from '../fn/semester-controller/delete-semester-by-id';
import { DeleteSemesterById$Params } from '../fn/semester-controller/delete-semester-by-id';
import { findAllSemesters } from '../fn/semester-controller/find-all-semesters';
import { FindAllSemesters$Params } from '../fn/semester-controller/find-all-semesters';
import { findMostRecentSemester } from '../fn/semester-controller/find-most-recent-semester';
import { FindMostRecentSemester$Params } from '../fn/semester-controller/find-most-recent-semester';
import { findPreviousYearSemester } from '../fn/semester-controller/find-previous-year-semester';
import { FindPreviousYearSemester$Params } from '../fn/semester-controller/find-previous-year-semester';
import { findSemesterById } from '../fn/semester-controller/find-semester-by-id';
import { FindSemesterById$Params } from '../fn/semester-controller/find-semester-by-id';
import { saveSemester } from '../fn/semester-controller/save-semester';
import { SaveSemester$Params } from '../fn/semester-controller/save-semester';
import { SemesterResponse } from '../models/semester-response';
import { updateSemesterById } from '../fn/semester-controller/update-semester-by-id';
import { UpdateSemesterById$Params } from '../fn/semester-controller/update-semester-by-id';

@Injectable({ providedIn: 'root' })
export class SemesterControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllSemesters()` */
  static readonly FindAllSemestersPath = '/semester';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllSemesters()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSemesters$Response(params?: FindAllSemesters$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SemesterResponse>>> {
    return findAllSemesters(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllSemesters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSemesters(params?: FindAllSemesters$Params, context?: HttpContext): Observable<Array<SemesterResponse>> {
    return this.findAllSemesters$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SemesterResponse>>): Array<SemesterResponse> => r.body)
    );
  }

  /** Path part for operation `saveSemester()` */
  static readonly SaveSemesterPath = '/semester';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveSemester()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveSemester$Response(params: SaveSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveSemester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveSemester$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveSemester(params: SaveSemester$Params, context?: HttpContext): Observable<number> {
    return this.saveSemester$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `copyWorkloadsFromSemester()` */
  static readonly CopyWorkloadsFromSemesterPath = '/semester/{targetSemesterId}/copy-workloads/{sourceSemesterId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `copyWorkloadsFromSemester()` instead.
   *
   * This method doesn't expect any request body.
   */
  copyWorkloadsFromSemester$Response(params: CopyWorkloadsFromSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return copyWorkloadsFromSemester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `copyWorkloadsFromSemester$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  copyWorkloadsFromSemester(params: CopyWorkloadsFromSemester$Params, context?: HttpContext): Observable<number> {
    return this.copyWorkloadsFromSemester$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `copyAcademicRanksFromSemester()` */
  static readonly CopyAcademicRanksFromSemesterPath = '/semester/{targetSemesterId}/copy-academic-ranks/{sourceSemesterId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `copyAcademicRanksFromSemester()` instead.
   *
   * This method doesn't expect any request body.
   */
  copyAcademicRanksFromSemester$Response(params: CopyAcademicRanksFromSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return copyAcademicRanksFromSemester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `copyAcademicRanksFromSemester$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  copyAcademicRanksFromSemester(params: CopyAcademicRanksFromSemester$Params, context?: HttpContext): Observable<number> {
    return this.copyAcademicRanksFromSemester$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findSemesterById()` */
  static readonly FindSemesterByIdPath = '/semester/{semesterId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findSemesterById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSemesterById$Response(params: FindSemesterById$Params, context?: HttpContext): Observable<StrictHttpResponse<SemesterResponse>> {
    return findSemesterById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findSemesterById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSemesterById(params: FindSemesterById$Params, context?: HttpContext): Observable<SemesterResponse> {
    return this.findSemesterById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SemesterResponse>): SemesterResponse => r.body)
    );
  }

  /** Path part for operation `deleteSemesterById()` */
  static readonly DeleteSemesterByIdPath = '/semester/{semesterId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSemesterById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSemesterById$Response(params: DeleteSemesterById$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return deleteSemesterById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSemesterById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSemesterById(params: DeleteSemesterById$Params, context?: HttpContext): Observable<number> {
    return this.deleteSemesterById$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateSemesterById()` */
  static readonly UpdateSemesterByIdPath = '/semester/{semesterId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSemesterById()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSemesterById$Response(params: UpdateSemesterById$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateSemesterById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSemesterById$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSemesterById(params: UpdateSemesterById$Params, context?: HttpContext): Observable<number> {
    return this.updateSemesterById$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findPreviousYearSemester()` */
  static readonly FindPreviousYearSemesterPath = '/semester/{semesterId}/previous-year';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findPreviousYearSemester()` instead.
   *
   * This method doesn't expect any request body.
   */
  findPreviousYearSemester$Response(params: FindPreviousYearSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<SemesterResponse>> {
    return findPreviousYearSemester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findPreviousYearSemester$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findPreviousYearSemester(params: FindPreviousYearSemester$Params, context?: HttpContext): Observable<SemesterResponse> {
    return this.findPreviousYearSemester$Response(params, context).pipe(
      map((r: StrictHttpResponse<SemesterResponse>): SemesterResponse => r.body)
    );
  }

  /** Path part for operation `findMostRecentSemester()` */
  static readonly FindMostRecentSemesterPath = '/semester/most-recent';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMostRecentSemester()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMostRecentSemester$Response(params?: FindMostRecentSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<SemesterResponse>> {
    return findMostRecentSemester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMostRecentSemester$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMostRecentSemester(params?: FindMostRecentSemester$Params, context?: HttpContext): Observable<SemesterResponse> {
    return this.findMostRecentSemester$Response(params, context).pipe(
      map((r: StrictHttpResponse<SemesterResponse>): SemesterResponse => r.body)
    );
  }

}
