/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcademicRankDetailsResponse } from '../../models/academic-rank-details-response';

export interface FindAcademicRankById1$Params {
  'academic-rank-id': number;
}

export function findAcademicRankById1(http: HttpClient, rootUrl: string, params: FindAcademicRankById1$Params, context?: HttpContext): Observable<StrictHttpResponse<AcademicRankDetailsResponse>> {
  const rb = new RequestBuilder(rootUrl, findAcademicRankById1.PATH, 'get');
  if (params) {
    rb.path('academic-rank-id', params['academic-rank-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AcademicRankDetailsResponse>;
    })
  );
}

findAcademicRankById1.PATH = '/academic-rank/details/{academic-rank-id}';
