/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcademicRankDetailsRequest } from '../../models/academic-rank-details-request';

export interface UpdateAcademicRankDetailsById$Params {
  'academic-rank-id': number;
      body: AcademicRankDetailsRequest
}

export function updateAcademicRankDetailsById(http: HttpClient, rootUrl: string, params: UpdateAcademicRankDetailsById$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, updateAcademicRankDetailsById.PATH, 'patch');
  if (params) {
    rb.path('academic-rank-id', params['academic-rank-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

updateAcademicRankDetailsById.PATH = '/academic-rank/details/{academic-rank-id}';
