/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetTeacherComparison$Params {
  semesterId?: number;
}

export function getTeacherComparison(http: HttpClient, rootUrl: string, params?: GetTeacherComparison$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
[key: string]: {
};
}>>> {
  const rb = new RequestBuilder(rootUrl, getTeacherComparison.PATH, 'get');
  if (params) {
    rb.query('semesterId', params.semesterId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      [key: string]: {
      };
      }>>;
    })
  );
}

getTeacherComparison.PATH = '/workload-stats/teacher-comparison';
