spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: ${DB_NAME}
    password: ${DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://${EC2_HOST}/auth/activate-account/
  cors:

    origins: http://${EC2_HOST}:8088, http://${EC2_HOST}:8080, http://${EC2_HOST}:80, http://${EC2_HOST}, http://${EC2_HOST},
server:
  port: 8088
