spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
application:
  security:
    jwt:
      secret-key: 92e84894f28a3acd33654f9965bd304e3c113722918863956580dc1e2dd956d63a44c502f355db926184dba089ae666f6a3c4d32b0e64055b415aaf05528f5b6379a149b2db58e992c265ada55e748cedee189e48f36fc532bb3c21625bafce216d6d137303ecd1e1ef484e8853e8f5cd267ab54c7feaf037e650857ea7eb601
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:

    origins: http://localhost:4200,http://localhost:8080,http://${EC2_HOST}:8088,http://${EC2_HOST}:8080, http://${EC2_HOST}:80, http://${EC2_HOST}
server:
  port: 8088
