/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkloadResponse } from '../../models/workload-response';

export interface FindWorkloadById$Params {
  workloadId: number;
}

export function findWorkloadById(http: HttpClient, rootUrl: string, params: FindWorkloadById$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkloadResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkloadById.PATH, 'get');
  if (params) {
    rb.path('workloadId', params.workloadId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkloadResponse>;
    })
  );
}

findWorkloadById.PATH = '/workload/{workloadId}';
