/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseObject } from '../../models/page-response-object';

export interface FindAllMyWorkloads$Params {
  page?: number;
  size?: number;
  sort?: string;
  direction?: string;
  filters?: string;
}

export function findAllMyWorkloads(http: HttpClient, rootUrl: string, params?: FindAllMyWorkloads$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseObject>> {
  const rb = new RequestBuilder(rootUrl, findAllMyWorkloads.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('filters', params.filters, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseObject>;
    })
  );
}

findAllMyWorkloads.PATH = '/workload/my-workloads';
