/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CopyAcademicRanksFromSemester$Params {
  targetSemesterId: number;
  sourceSemesterId: number;
}

export function copyAcademicRanksFromSemester(http: HttpClient, rootUrl: string, params: CopyAcademicRanksFromSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, copyAcademicRanksFromSemester.PATH, 'post');
  if (params) {
    rb.path('targetSemesterId', params.targetSemesterId, {});
    rb.path('sourceSemesterId', params.sourceSemesterId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

copyAcademicRanksFromSemester.PATH = '/semester/{targetSemesterId}/copy-academic-ranks/{sourceSemesterId}';
