/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SemesterResponse } from '../../models/semester-response';

export interface FindMostRecentSemester$Params {
}

export function findMostRecentSemester(http: HttpClient, rootUrl: string, params?: FindMostRecentSemester$Params, context?: HttpContext): Observable<StrictHttpResponse<SemesterResponse>> {
  const rb = new RequestBuilder(rootUrl, findMostRecentSemester.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SemesterResponse>;
    })
  );
}

findMostRecentSemester.PATH = '/semester/most-recent';
