/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SemesterResponse } from '../../models/semester-response';

export interface FindAllSemesters$Params {
}

export function findAllSemesters(http: HttpClient, rootUrl: string, params?: FindAllSemesters$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SemesterResponse>>> {
  const rb = new RequestBuilder(rootUrl, findAllSemesters.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SemesterResponse>>;
    })
  );
}

findAllSemesters.PATH = '/statuses';
