/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FacultyResponse } from '../../models/faculty-response';

export interface FindFacultyById$Params {
  facultyId: number;
}

export function findFacultyById(http: HttpClient, rootUrl: string, params: FindFacultyById$Params, context?: HttpContext): Observable<StrictHttpResponse<FacultyResponse>> {
  const rb = new RequestBuilder(rootUrl, findFacultyById.PATH, 'get');
  if (params) {
    rb.path('facultyId', params.facultyId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FacultyResponse>;
    })
  );
}

findFacultyById.PATH = '/faculty/{facultyId}';
