/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FacultyResponse } from '../../models/faculty-response';

export interface GetFaculties$Params {
}

export function getFaculties(http: HttpClient, rootUrl: string, params?: GetFaculties$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FacultyResponse>>> {
  const rb = new RequestBuilder(rootUrl, getFaculties.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FacultyResponse>>;
    })
  );
}

getFaculties.PATH = '/faculty';
