/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkloadSettingsResponse } from '../../models/workload-settings-response';

export interface FindWorkloadSettingsById$Params {
  workloadSettingsId: number;
}

export function findWorkloadSettingsById(http: HttpClient, rootUrl: string, params: FindWorkloadSettingsById$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkloadSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkloadSettingsById.PATH, 'get');
  if (params) {
    rb.path('workloadSettingsId', params.workloadSettingsId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkloadSettingsResponse>;
    })
  );
}

findWorkloadSettingsById.PATH = '/workload-settings/{workloadSettingsId}';
